### ISSUE TITLE
[REQUEST] Onju Voice PCB variant for the Google Home Mini (1st gen) speaker with Micro-USB charging port

### ISSUE THREAD

**Issue by Hedda** [justLV/onju-voice#27]
Please consider designing/making an Onju Voice PCB variant for the Google Home Mini (1st gen) with a Micro-USB charging port.

https://www.ifixit.com/Device/Google_Home_Mini

https://www.ifixit.com/Guide/Google+Home+Mini+Disassembly/109922

https://www.ifixit.com/Teardown/Google+Home+Mini+Teardown/102264

FCC ID A4R-H0A

https://fccid.io/A4RH0A

https://fcc.report/FCC-ID/A4RH0A

Bet quite a few people like myself also own many of the first-generation Google Nest Mini and are interested in converting them.

https://www.dimensions.com/element/google-home-mini

The downsides to the first-generation Google Home Mini are a worse speaker and worse speaker array compared to the newer generation, (as well as that Micro-USB charging port however you would probably want to still keep it a Micro-USB charging port since all of them shipped with a Micro-USB charger power-adapter).

https://en.wikipedia.org/wiki/Google_Nest_(smart_speakers)

https://support.google.com/googlenest/answer/7072284

**Comment by Batman313v** [comment]
Hi, First gen owner here. I love upcycling and would love to upcycle my gen 1 minis into being useful again. I followed a project for a while that attempted to make custom firmware for the default hardware but it ultimatly fell through. I love the idea of this as a HASS user but also as a ML dev. I have my own bot that currently runs on an old gaming laptop (working on integrating it with the native HASS "Assist"). Enough background. My main quiestion is this: Does anyone know what would prevent this board from working with the Gen 1 hardware? They appear to be the same size, have the LEDs in approx (if not exactly) the same location, etc. But it looks as though it may just fit in place. It may not be perfect but I'm assuming nothing a dremel couldn't fix..? I'm assuming the ribbon cable for the power delivery board would be different but other then that I can't (immediately) see anything that would prevent it. Maybe we could come up with a list of things that would need to change to help the dev process. I only have gen 1 devices so I can't really compair against anything other then some photos.

I would love for there to be an alternate version with a USB-C port as well as I have attempted to migrate all my devices towards that standard but that may have to come later.

**Comment by sarus3749** [comment]
Hello.
I've also this GHmini and I'd love to have a new variant of your PCB for this device. You're doing an amazing job ! Thank you for this :)

**Comment by arunoruto** [comment]
Seems like there has been a faulty update for the original Home Mini, where devices got bricked ([9to5google](https://9to5google.com/2023/12/23/google-home-mini-update-bricked-devices/)). With more devices being bricked, it would be awesome to have an alternative way to use the hardware!

The cost of 5 PCBs isn't small (around 80€-85€ with components), but maybe I will make the investment and test out what is preventing the usage of the PCB. I was looking at images of both PCBs, and they are mostly similar.

**Comment by toxic0berliner** [comment]
Very interested in a home mini gen 1 version too here. In France they go on the used market regularly for 10€ but I have never seen a gen2 go for under 25€ most ask 30€
I already have 8 of the gen1 at home and using it happily with Google just sad I can't run it locally as most everything I do is triggering HA devices from GH... (And listen to music which might also come one day to the onju 😁)
I'm ready to try it out and happy to shell out the ~90€ for 5 boards but not so much 5x30=150€ for the shell... 

Really hoping someone with more skills than me can make a gen1 version of this ❤️

**Comment by bobzer** [comment]
Unfortunately, I don't know how to correctly modify the pcb and test it to be able to order it from pcbway. But I tried the violent way... which mean just cut and try to force fit the pcb inside the google home mini 1st gen.
So i notice a few things :
- the connector for power and mute button is not the same
  - but not difficult to solder a small cable to make it work. (we could also solder the data pin but harder)
- size of the board :
  - the hole for the screw close to the ribbon connector is correctly place 
  - the two holes close to the led are not bad, they are correctly align but not the correct width, I make them a little bit bigger.
  - the last one is not useable
- the buttons boot and reset (on the pcb) are exactly under bump of the metal support of the speaker, so you need to remove that bump
- the touch buttons :
  - both side could work if extend with some cable and adjust the value of the esp touch config
    - at some point I broke one of them, i'm not 100% sure how, but probably when i drill to increase the size of the screw hole. 
  - the center, i never was able to make it work
- the leds works except the one from the side because not on the correct side of the pcb so not visible
