### ISSUE TITLE
Antenna choice?

### ISSUE THREAD

**Issue by eabase** [justLV/onju-voice#7]
How's the antenna performance on this design? 
I'm asking because it seem a bit strange choice for using such a low gain antenna. 

The one specified in your current design datasheet say that the gain is: `-0.5 dBi`, which is very bad. 
I would rather suggest something using uFL connector with a gain of at least a `2.0 dBi`. 
Maybe something like:
* [this](https://www.data-alliance.net/wifi-antenna-dual-band-w-ufl-connector/) (`2.0 dBi`)
* or [Ignion NANO mXTEND™ (NN02-101)](https://ignion.io/files/DS_NN02-101.pdf) (`2.4 dBi`)

**Comment by justLV** [comment]
I found the antenna has worked well enough for me even with uncompressed audio. 

I did a crude throughput test comparing to an ESP32-S3 devboard with a uFL and didn't see any significant difference.
(Also a uFL is a little more thought and testing to get into the form factor with minimal edits to the shell)

Improvements I made to the board were around 40MHz crystal stability which made a massive difference and I haven't had any issues since.

Re: component choice, I chose it mostly due to familiarity and being easy to source. I saw the Ignion antennas in a few products but haven't tried them. There's also the NN01-102.

You're also comparing the peak gain of the ignion to the average gain of the Johannson.

Would you like to design in the NN02-101?
